services:
  tyk-redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - tyk-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10
  tyk-gateway:
    image: tykio/tyk-gateway:v5.9
    ports:
      - "8888:8080"
      - "9696:9696"
    environment:
      - TYK_GW_SECRET=352d20ee67be67f6340b4c0605b044b7
      - TYK_GW_STORAGE_TYPE=redis
      - TYK_GW_STORAGE_ADDRS=tyk-redis:6379
      - TYK_GW_ENABLEAPI=true
      - TYK_GW_CONTROLAPIPORT=9696
    volumes:
      - ./tyk/apps:/opt/tyk-gateway/apps
    depends_on:
      tyk-redis:
        condition: service_healthy
    networks:
      - tyk-network
  go-webservice:
    image: go-webservice
    ports:
      - "8080:8080"
    networks:
      - tyk-network
    restart: unless-stopped

networks:
  tyk-network:
    driver: bridge

volumes:
  redis-data:
